### ISSUE TITLE
Update specification for simulator

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/everest-spe-rsc-2025#7]
Update config to new EVEREST version:

```
everest: error: Loading config file <config_opm.yml> failed with:
Found 1 validation error:

simulator
    * Value error, Queue system configuration has changed, valid options for lsf are: ['name', 'max_running', 'submit_sleep', 'project_code', 'activate_script', 'bhist_cmd', 'bjobs_cmd', 'bkill_cmd', 'bsub_cmd', 'exclude_host', 'lsf_queue', 'lsf_resource'] (type=value_error)
```
It should be 
```
simulator:
  queue_system:
    name: lsf
    max_running: 200
```
